GET http://localhost:4004/catalog/Book

#####
GET http://localhost:4004/catalog/Book/11


###
POST http://localhost:4004/catalog/Book
Content-Type: application/json

{"ID":11,"Books_Title":"Physices","Price":500}

###
PATCH  http://localhost:4004/catalog/Book/11
Content-Type: application/json

{"ID": 11,"Books_Title":"Physices","Price":200}

######
DELETE http://localhost:4004/catalog/Book/11